name: CI android
on:
  push:
    branches:
      - mockWebServer

jobs:
  build-and-test:
    name: Build and run tests
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 29 ]
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2.26.0
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86
          profile: Pixel 2
          avd-name: test
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          disable-animations: true
          script: ./gradlew connectedCheck --stacktrace
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/